# Generated by Django 3.2.8 on 2021-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('number_of_people', models.IntegerField(blank=True)),
                ('explain', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('Netflix', 'Netflix'), ('Watcha', 'Watcha'), ('Wave', 'Wave'), ('Tving', 'Tving'), ('Disney plus', 'Disney')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
