# Generated by Django 3.2.8 on 2021-11-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Netflix', 'Netflix'), ('Watcha', 'Watcha'), ('Wave', 'Wave'), ('Tving', 'Tving'), ('Disney plus', 'Disney')], max_length=20),
        ),
    ]
