# Generated by Django 3.2.8 on 2021-11-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211111_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='OttType',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.OttType'),
        ),
    ]
