# Generated by Django 3.2.8 on 2021-11-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='OttType',
        ),
        migrations.AddField(
            model_name='post',
            name='OttType',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.otttype'),
            preserve_default=False,
        ),
    ]
