# Generated by Django 3.2.8 on 2021-11-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20211113_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_people',
            field=models.IntegerField(),
        ),
    ]
